#0. Install

In [ ]:
import numpy as np
import pandas as pd

from scipy.stats import norm
from os import path

# 1. Data Preparation

##Base Data loading

In [ ]:
#Base Data loading

#files path
base_path = 'Base_data_csv_files'

### Dimentins: Week, Geo
Holidays_SalesSpike_df_path = base_path + '/Holidays_SalesSpike.csv'
TotalDemandSeasonality_df_path = base_path + '/TotalDemandSeasonality.csv'
Demand_df_path = base_path + '/Demand.csv'
LiftRatio_UnitCost_TV_df_path = base_path + '/LiftRatio_UnitCost_TV.csv'
Population_df_path = base_path + '/Population.csv'
ViewRatioFlyer_df_path = base_path + '/ViewRatioFlyer.csv'

### Dimentions: Year, Media
MediaPlan_df_path = base_path + '/MediaPlan.csv'
### Dimention: Media
MediaPlan_threshold_df_path = base_path + '/MediaPlan_threshold.csv'

### Dimentin: geo
UnitCost_by_geo_df_path = base_path + '/UnitCost_by_geo.csv'
Share_by_geo_df_path = base_path + '/Share_by_geo.csv'

### Dimentin: Week
PurchaseRatio_df_path = base_path + '/PurchaseRatio.csv'
CouponResponseRatio_df_path = base_path + '/CouponResponseRatio.csv'

### Dimentins: mu, sd
mu_sd_df_path = base_path + '/mu_sd.csv'
mu_sd_df_without_noise_after_spend_df_path = base_path + '/mu_sd_sd0_AfterSpend.csv'

#Dataframe from each csv files
Holidays_SalesSpike_df = pd.read_csv(Holidays_SalesSpike_df_path)
TotalDemandSeasonality_df = pd.read_csv(TotalDemandSeasonality_df_path)
Demand_df = pd.read_csv(Demand_df_path)
LiftRatio_UnitCost_TV_df = pd.read_csv(LiftRatio_UnitCost_TV_df_path)
Population_df = pd.read_csv(Population_df_path)
ViewRatioFlyer_df = pd.read_csv(ViewRatioFlyer_df_path)

MediaPlan_df = pd.read_csv(MediaPlan_df_path)
MediaPlan_threshold_df = pd.read_csv(MediaPlan_threshold_df_path)

UnitCost_by_geo_df = pd.read_csv(UnitCost_by_geo_df_path)
Share_by_geo_df = pd.read_csv(Share_by_geo_df_path)

PurchaseRatio_df = pd.read_csv(PurchaseRatio_df_path)
CouponResponseRatio_df = pd.read_csv(CouponResponseRatio_df_path)

mu_sd_df = pd.read_csv(mu_sd_df_path)
mu_sd_df_without_noise_after_spend_df = pd.read_csv(mu_sd_df_without_noise_after_spend_df_path)

##mu and sd

In [ ]:
mu_sd_df = mu_sd_df.rename(columns={'Unnamed: 0': 'Metric'})

In [ ]:
pd.set_option('display.max_columns', None)
display(mu_sd_df)
pd.reset_option('display.max_columns')

,Metric,TotalDemandSeasonality(Intentionaly),Executed_TV,Executed_Digital,Executed_Flyer,Spend_TV,Spend_Digital,Spend_Flyer,Impression_TV_Young,Impression_TV_Middle,Impression_TV_Elder,Impression_Digital_Young,Impression_Digital_Middle,Impression_Digital_Elder,Impression_Flyer_Young,Impression_Flyer_Middle,Impression_Flyer_Elder,Frequency_TV,Frequency_Digital,Frequency_Flyer,View_Flyer_Young_Directly,View_Flyer_Middle_Directly,View_Flyer_Elder_Directly,View_Flyer_Young_viaTV,View_Flyer_Middle_viaTV,View_Flyer_Elder_viaTV,View_Flyer_Young_viaDigital,View_Flyer_Middle_viaDigital,View_Flyer_Elder_viaDigital,Sales_TV_Young,Sales_TV_Middle,Sales_TV_Elder,Sales_Digital_Young,Sales_Digital_Middle,Sales_Digital_Elder,Sales_Flyer_Young,Sales_Flyer_Middle,Sales_Flyer_Elder,Sales_Flyer_Directly_Young,Sales_Flyer_Directly_Middle,Sales_Flyer_Directly_Elder,Sales_Flyer_viaTV_Young,Sales_Flyer_viaTV_Middle,Sales_Flyer_viaTV_Elder,Sales_Flyer_viaDigital_Young,Sales_Flyer_viaDigital_Middle,Sales_Flyer_viaDigital_Elder,CouponUsed_viaDigital_Young,CouponUsed_viaDigital_Middle,CouponUsed_viaDigital_Elder,CouponUsed_viaFlyer_Directly_Young,CouponUsed_viaFlyer_Directly_Middle,CouponUsed_viaFlyer_Directly_Elder,CouponUsed_viaFlyer_viaTV_Young,CouponUsed_viaFlyer_viaTV_Middle,CouponUsed_viaFlyer_viaTV_Elder,CouponUsed_viaFlyer_viaDigital_Young,CouponUsed_viaFlyer_viaDigital_Middle,CouponUsed_viaFlyer_viaDigital_Elder
0,mu,1.00,1.0,1.0,1.0,1,1.00,1,1.00,NaN,1.000,1.000,NaN,1.00,1.00,NaN,1.000,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,sd,0.01,0.2,0.2,0.1,0,0.01,0,0.05,NaN,0.001,0.001,NaN,0.03,0.05,NaN,0.001,0.05,0.05,0.01,0.02,0.05,0.01,0.02,0.05,0.01,0.02,0.05,0.01,0.05,0.05,0.1,0.2,0.2,0.2,0.1,0.2,0.2,0.1,0.2,0.2,0.1,0.2,0.2,0.1,0.2,0.2,0.1,0.15,0.2,0.3,0.2,0.1,0.3,0.2,0.1,0.3,0.2,0.1

##External Fixed Parameter

In [ ]:
α1 = 38518 #Spend_Digital
α2 = 1.4669 #Spend_Digital
α3 = 2.5 #Spend_Flyer

α4 = 1.2376 #Frequency_TV
α5 = 0.0014 #Frequency_TV
α6 = 1.5511 #Frequency_Digital
α7 = 0.003 #Frequency_Digital

α8 = 0.1 #Baseline

##Decay Rate of Flyer Adstock

In [ ]:
decay_rate_Flyer_Young_L1 = 0.5
decay_rate_Flyer_Middle_L1 = 0.5
decay_rate_Flyer_Elder_L1 = 0.5

decay_rate_Flyer_Young_L2 = 0.5
decay_rate_Flyer_Middle_L2 = 0.5
decay_rate_Flyer_Elder_L2 = 0.5

decay_rate_Flyer_Young_L3 = 0.5
decay_rate_Flyer_Middle_L3 = 0.5
decay_rate_Flyer_Elder_L3 = 0.5

##UnitSales (Incremental Unit Price)

In [ ]:
UnitSales_TV_Young = 5
UnitSales_TV_Middle = 5
UnitSales_TV_Elder = 5

UnitSales_Digital_Young = 5
UnitSales_Digital_Middle = 5
UnitSales_Digital_Elder = 5

UnitSales_Flyer_Young = 5
UnitSales_Flyer_Middle = 5
UnitSales_Flyer_Elder = 5

UnitSales_Coupon_viaFlyer_Young = 5
UnitSales_Coupon_viaFlyer_Middle = 5
UnitSales_Coupon_viaFlyer_Elder = 5

UnitSales_Coupon_viaDigital_Young = 5
UnitSales_Coupon_viaDigital_Middle = 5
UnitSales_Coupon_viaDigital_Elder = 5

##CouponDiscountRate

In [ ]:
#Note: The discount rate is in decimal form.
CouponDiscountRate_viaFlyer_Young = 0.05
CouponDiscountRate_viaFlyer_Middle = 0.05
CouponDiscountRate_viaFlyer_Elder = 0.05

CouponDiscountRate_viaDigital_Young = 0.05
CouponDiscountRate_viaDigital_Middle = 0.05
CouponDiscountRate_viaDigital_Elder = 0.05

# 2. Creating Simulation Data

##Merge Base Data

In [ ]:
Population_df = Population_df.rename(columns={'geo': 'Geo'})
Population_df = Population_df.rename(columns={'week': 'Week'})

PurchaseRatio_df = PurchaseRatio_df.rename(columns=lambda col: col if col == 'Unnamed: 0' else 'ConversionRate_' + col)
PurchaseRatio_df = PurchaseRatio_df.rename(columns={'Unnamed: 0': 'Week'})

CouponResponseRatio_df = CouponResponseRatio_df.rename(columns=lambda col: col if col == 'Unnamed: 0' else 'CouponRedemptionRate_' + col)
CouponResponseRatio_df = CouponResponseRatio_df.rename(columns={'Unnamed: 0': 'Week'})

UnitCost_by_geo_df = UnitCost_by_geo_df.rename(columns={'geo': 'Geo'})
Share_by_geo_df = Share_by_geo_df.rename(columns={'geo': 'Geo'})

In [ ]:
# Merge the dataframes
df = pd.merge(Holidays_SalesSpike_df, TotalDemandSeasonality_df, on=['Geo', 'Week'], how='inner')
df = pd.merge(df, Demand_df, on=['Geo', 'Week'], how='inner')
df = pd.merge(df, LiftRatio_UnitCost_TV_df, on=['Geo', 'Week'], how='inner')
df = pd.merge(df, Population_df, on=['Geo', 'Week'], how='inner')
df = pd.merge(df, ViewRatioFlyer_df, on=['Geo', 'Week'], how='inner')

# Display the merged dataframeh
df.head()

,Geo,Week,Holidays,DemandShock,TotalDemandSeasonality,TotalDemand,TotalGeoDemand,CostMultiplier_TV,Population,Pop_Young,Pop_Middle,Pop_Elder,ViewRate_Flyer_Young,ViewRate_Flyer_Middle,ViewRate_Flyer_Elder
0,1,3/1/2021,0,0,0.966291,0.964059,4.661643e+07,1.0,36227.421289,9404.743939,14895.100585,11927.576771,0.347367,0.561553,0.765927
1,1,3/8/2021,0,0,0.979547,0.977021,4.724316e+07,1.0,36222.977347,9403.584953,14891.261735,11928.130664,0.345555,0.558768,0.763744
2,1,3/15/2021,0,0,1.011943,1.009201,4.879920e+07,1.0,36215.793032,9398.795409,14888.068705,11928.928921,0.343767,0.556030,0.761597
3,1,3/22/2021,0,0,1.018055,1.036003,5.009520e+07,1.0,36208.608718,9394.005866,14884.875675,11929.727179,0.342002,0.553340,0.759484
4,1,3/29/2021,0,0,0.941146,0.950452,4.595847e+07,1.0,36201.424403,9389.216322,14881.682645,11930.525436,0.340261,0.550698,0.757407

##Media Plan

###Total Impression

In [ ]:
# Get mu and sd values from mu_sd_df
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['TotalDemandSeasonality(Intentionaly)'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['TotalDemandSeasonality(Intentionaly)'].iloc[0]

# Fix the random seed for reproducibility
np.random.seed(42)

# Calculate the new column
df['TotalDemandSeasonality(intentionaly)'] = df['TotalDemandSeasonality'] * (norm.ppf(np.random.rand(len(df))) * sd + mu)

In [ ]:
MediaPlan_threshold_df = MediaPlan_threshold_df.rename(columns={'Unnamed: 0': 'Plan'})

In [ ]:
MediaPlan_df

,Year,Media,Normal Period,Low Intensity,Medium Intensity,High Intensity,Holidays
0,2020,TV,0,0,300,500,0
1,2021,TV,0,0,280,450,0
2,2022,TV,0,0,280,400,0
3,2023,TV,0,0,150,400,0
4,2024,TV,0,0,150,350,0
5,2020,Digital,0,80,120,200,0
6,2021,Digital,40,80,120,200,0
7,2022,Digital,40,100,140,220,0
8,2023,Digital,60,100,140,240,120
9,2024,Digital,80,100,140,280,120
10,2020,Flyer,0,20,20,60,60
11,2021,Flyer,0,15,15,50,50
12,2022,Flyer,0,10,10,40,40
13,2023,Flyer,0,10,10,40,40
14,2024,Flyer,0,0,0,40,40

In [ ]:
MediaPlan_threshold_df

               Plan     TV  Digital  Flyer
0     Normal Period  0.968    0.968  0.968
1     Low Intensity  1.008    1.008  1.008
2  Medium Intensity  1.048    1.048  1.048
3    High Intensity  1.088    1.088  1.088

In [ ]:
def assign_plan_type_revised(total_demand_seasonality, thresholds, Media):
    """Assigns a media plan based SOLELY on TotalDemandSeasonality and thresholds."""

    if total_demand_seasonality > thresholds[thresholds['Plan'] == 'High Intensity'][Media].iloc[0]:
        return 'High Intensity'
    elif total_demand_seasonality > thresholds[thresholds['Plan'] == 'Medium Intensity'][Media].iloc[0]:
        return 'Medium Intensity'
    elif total_demand_seasonality > thresholds[thresholds['Plan'] == 'Low Intensity'][Media].iloc[0]:
        return 'Low Intensity'
    elif total_demand_seasonality > thresholds[thresholds['Plan'] == 'Normal Period'][Media].iloc[0]:
        return 'Normal Period'
    else:
        return 'NoSpend_Period'

df['Type_of_Plan_TV'] = df.apply(
    lambda row: assign_plan_type_revised(
        row['TotalDemandSeasonality(intentionaly)'],
        MediaPlan_threshold_df,
        'TV'
    ),
    axis=1
)

df['Type_of_Plan_Digital'] = df.apply(
    lambda row: assign_plan_type_revised(
        row['TotalDemandSeasonality(intentionaly)'],
        MediaPlan_threshold_df,
        'Digital'
    ),
    axis=1
)

df['Type_of_Plan_Flyer'] = df.apply(
    lambda row: assign_plan_type_revised(
        row['TotalDemandSeasonality(intentionaly)'],
        MediaPlan_threshold_df,
        'Flyer'
    ),
    axis=1
)

In [ ]:
def get_media_plan_value_revised(row, media_plan_df, media):
    week = pd.to_datetime(row['Week'])
    year = week.year

    # Adjust the year for the fiscal year starting on April 1st.
    if week.month < 4:
        plan_year = year - 1
    else:
        plan_year = year

    plan_type_column = f'Type_of_Plan_{media}'
    seasonality_plan_type = row[plan_type_column]

    if seasonality_plan_type == 'NoSpend_Period':
        seasonality_value = 0
    else:
        seasonality_value = media_plan_df[
            (media_plan_df['Year'] == plan_year) &
            (media_plan_df['Media'] == media)
        ][seasonality_plan_type].iloc[0]

    # In the case of Holidays
    if row['Holidays'] == 1:
        holiday_value = media_plan_df[
            (media_plan_df['Year'] == plan_year) &
            (media_plan_df['Media'] == media)
        ]['Holidays'].iloc[0]

        # The final value will be the higher of the seasonality cost and the holiday cost.
        return max(seasonality_value, holiday_value)

    else:
        return seasonality_value

df['Plan_TV'] = df.apply(lambda row: get_media_plan_value_revised(row, MediaPlan_df, 'TV'), axis=1)
df['Plan_Digital'] = df.apply(lambda row: get_media_plan_value_revised(row, MediaPlan_df, 'Digital'), axis=1)
df['Plan_Flyer'] = df.apply(lambda row: get_media_plan_value_revised(row, MediaPlan_df, 'Flyer'), axis=1)

In [ ]:
# Get mu and sd values from mu_sd_df
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Executed_TV'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Executed_TV'].iloc[0]
# Calculate the new column
df['Executed_TV'] = df['Plan_TV'] * (norm.ppf(np.random.rand(len(df))) * sd + mu)

# Get mu and sd values from mu_sd_df
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Executed_Digital'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Executed_Digital'].iloc[0]
# Calculate the new column
df['Executed_Digital'] = df['Plan_Digital'] * (norm.ppf(np.random.rand(len(df))) * sd + mu)

# Get mu and sd values from mu_sd_df
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Executed_Flyer'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Executed_Flyer'].iloc[0]
# Calculate the new column
df['Executed_Flyer'] = df['Plan_Flyer'] *(norm.ppf(np.random.rand(len(df))) * sd + mu)

In [ ]:
UnitCost_by_geo_df

    Geo  UnitCost_TV  UnitCost_Flyer
0     1       155000           10.75
1     2        38750           10.79
2     3        72850           11.49
3     4         4650           10.35
4     5        20150           10.46
5     6        17050           10.74
6     7         4650           11.35
7     8         4650           11.89
8     9         7750           10.79
9    10         3100           11.87
10   11         3100           11.25
11   12         6200           10.83
12   13         7750           10.67
13   14         3100           12.24
14   15         4650           12.06
15   16         3100           12.24
16   17         7750           13.35
17   18        12400           11.30
18   19         6200           10.33
19   20         9300           10.33
20   21         4650           11.17
21   22         3100           10.53
22   23         4650           10.21
23   24         3100           10.16
24   25         4650           10.84
25   26         6200           10.14
26   27         3100           10.35
27   28         3100            9.80
28   29         4650           11.39
29   30         4650           13.23

In [ ]:
# Merge df with UnitCost_by_geo_df on 'Geo' to get UnitCost_TV
df = pd.merge(df, UnitCost_by_geo_df, on=['Geo'], how='inner')

# Calculate the new UnitCost_TV column
df['UnitCost_TV'] = df['UnitCost_TV'] * df['CostMultiplier_TV']

In [ ]:
# Calculate Impression
df['Impression_TV'] = df['Executed_TV'] * df['Population'] /100
df['Impression_Digital'] = df['Executed_Digital'] * df['Population'] /100
df['Impression_Flyer'] = df['Executed_Flyer'] * df['Population'] /100

###Spend

In [ ]:
# Calculate National Population by week
national_population_df = df.groupby('Week')['Population'].sum().reset_index()
national_population_df = national_population_df.rename(columns={'Population': 'National_Population'})

# Merge National Population back to the main dataframe
df = pd.merge(df, national_population_df, on='Week', how='left')

In [ ]:
# Calculate Spend
df['Spend_TV'] = np.where(df['Executed_TV'] == 0, 0, (df['Executed_TV'] * df['UnitCost_TV']) / 1000)

# Get mu and sd values from mu_sd_df
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Spend_Digital'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Spend_Digital'].iloc[0]

df['Spend_Digital'] = np.where(df['Executed_Digital'] == 0, 0,
                               (α1 * df['Executed_Digital'] **α2) * (norm.ppf(np.random.rand(len(df))) * sd + mu) * df['Population'] / df['National_Population'] /1000 )

df['Spend_Flyer'] = df['Impression_Flyer']*1000 /α3 *df['UnitCost_Flyer'] /1000

###Impression by gen

In [ ]:
#Young and Elder
# Define the lists of media types and segments to process
media_types = ['TV', 'Digital', 'Flyer']
segments = ['Young', 'Elder']

# Outer loop to iterate through each media type
for media in media_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names using f-strings from the media and segment names
        mu_sd_column = f'Impression_{media}_{segment}'
        population_column = f'Pop_{segment}'
        base_impression_column = f'Impression_{media}'
        new_impression_column = f'Impression_{media}_{segment}'

        # Get mu and sd values
        mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][mu_sd_column].iloc[0]
        sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][mu_sd_column].iloc[0]

        # Calculate the new column and add it to the DataFrame
        df[new_impression_column] = (df[base_impression_column] *
                                     df[population_column] /
                                     df['Population'] *
                                     (norm.ppf(np.random.rand(len(df))) * sd + mu))

#Middle
df['Impression_TV_Middle'] = df['Impression_TV'] - df['Impression_TV_Young'] - df['Impression_TV_Elder']
df['Impression_Digital_Middle'] = df['Impression_Digital'] - df['Impression_Digital_Young'] - df['Impression_Digital_Elder']
df['Impression_Flyer_Middle'] = df['Impression_Flyer'] - df['Impression_Flyer_Young'] - df['Impression_Flyer_Elder']


#Column reordering
columns = df.columns.tolist()
columns = columns[:-9]
new_order = [
    'Impression_TV_Young',
    'Impression_TV_Middle',
    'Impression_TV_Elder',
    'Impression_Digital_Young',
    'Impression_Digital_Middle',
    'Impression_Digital_Elder',
    'Impression_Flyer_Young',
    'Impression_Flyer_Middle',
    'Impression_Flyer_Elder'
]
columns.extend(new_order)
df = df[columns]

###Frequency

In [ ]:
#TV
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Frequency_TV'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Frequency_TV'].iloc[0]
df['Frequency_TV'] = np.where(df['Executed_TV'] == 0, 0, α4 * np.exp(α5 * df['Executed_TV']) * (norm.ppf(np.random.rand(len(df))) * sd + mu))

#Digital
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Frequency_Digital'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Frequency_Digital'].iloc[0]
df['Frequency_Digital'] = np.where(df['Executed_Digital'] == 0, 0, α6 * np.exp(α7 * df['Executed_Digital']) * (norm.ppf(np.random.rand(len(df)))* sd + mu))

#Flyer
mu = mu_sd_df[mu_sd_df['Metric'] == 'mu']['Frequency_Flyer'].iloc[0]
sd = mu_sd_df[mu_sd_df['Metric'] == 'sd']['Frequency_Flyer'].iloc[0]
df['Frequency_Flyer'] = np.where(df['Executed_Flyer'] == 0, 0, (norm.ppf(np.random.rand(len(df))) * sd + mu))

###Reach

In [ ]:
# Define the lists of media types and segments to process
media_types = ['TV', 'Digital', 'Flyer']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each media type
for media in media_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names using f-strings from the media and segment names
        impression_column = f'Impression_{media}_{segment}'
        frequency_column = f'Frequency_{media}'
        new_reach_column = f'Reach_{media}_{segment}'


        # Calculate the new column and add it to the DataFrame
        df[new_reach_column] = np.where(df[frequency_column] == 0, 0, df[impression_column]/df[frequency_column])

In [ ]:
# Define the lists of media types and segments to process
media_types = ['Flyer']
segments = ['Young', 'Middle', 'Elder']

geo_column = 'Geo'

# Outer loop to iterate through each media type
for media in media_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names
        base_reach_column = f'Reach_{media}_{segment}'
        decay_rate_L1 = eval(f'decay_rate_{media}_{segment}_L1')
        decay_rate_L2 = eval(f'decay_rate_{media}_{segment}_L2')
        decay_rate_L3 = eval(f'decay_rate_{media}_{segment}_L3')
        new_reach_L1_column = f'Reach_{media}_{segment}_L1'
        new_reach_L2_column = f'Reach_{media}_{segment}_L2'
        new_reach_L3_column = f'Reach_{media}_{segment}_L3'

        # L1: For each geo, set the new_reach_L1_column to 0 for the first week.
        df[new_reach_L1_column] = df.groupby(geo_column)[base_reach_column].transform(lambda x: x.shift(1).fillna(0)) * decay_rate_L1

        # L2: For each geo, set the new_reach_L2_column to 0 for the first to 2nd week.
        df[new_reach_L2_column] = df.groupby(geo_column)[new_reach_L1_column].transform(lambda x: x.shift(1).fillna(0)) * decay_rate_L2

        # L3: For each geo, set the new_reach_L2_column to 0 for the first to 3rd week.
        df[new_reach_L3_column] = df.groupby(geo_column)[new_reach_L2_column].transform(lambda x: x.shift(1).fillna(0)) * decay_rate_L3

#Column reordering
columns = df.columns.tolist()
columns = columns[:-9]
new_order = [
    'Reach_Flyer_Young_L1',
    'Reach_Flyer_Middle_L1',
    'Reach_Flyer_Elder_L1',
    'Reach_Flyer_Young_L2',
    'Reach_Flyer_Middle_L2',
    'Reach_Flyer_Elder_L2',
    'Reach_Flyer_Young_L3',
    'Reach_Flyer_Middle_L3',
    'Reach_Flyer_Elder_L3'
]
columns.extend(new_order)
df = df[columns]

In [ ]:
decay_rate_L1

0.5

### View Flyer

In [ ]:
#View_Flyer Directly
# Define the lists of media types and segments to process
path_types = ['Directly']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each path
for path in path_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names using f-strings from the segment and path names
        ViewRate_Flyer_column = f'ViewRate_Flyer_{segment}'
        base_reach_Flyer_column = f'Reach_Flyer_{segment}'
        L1_reach_Flyer_column = f'Reach_Flyer_{segment}_L1'
        L2_reach_Flyer_column = f'Reach_Flyer_{segment}_L2'
        L3_reach_Flyer_column = f'Reach_Flyer_{segment}_L3'
        new_View_Flyer_column = f'View_Flyer_{segment}_{path}'

        # Get mu and sd values
        mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_View_Flyer_column].iloc[0]
        sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_View_Flyer_column].iloc[0]

        # Calculate the new column and add it to the DataFrame
        df[new_View_Flyer_column] = (
            (df[base_reach_Flyer_column] + df[L1_reach_Flyer_column] + df[L2_reach_Flyer_column] + df[L3_reach_Flyer_column]) *
            df[ViewRate_Flyer_column] *
              (norm.ppf(np.random.rand(len(df))) * sd + mu)
        )

In [ ]:
#View_Flyer viaTV and via Digital
# Define the lists of media types and segments to process
path_types = ['TV','Digital']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each path types
for path in path_types:
  # Inner loop to iterate through each segment
  for segment in segments:
      # Dynamically generate column names using f-strings from the media and segment names
      ViewRate_Flyer_column = f'ViewRate_Flyer_{segment}'
      base_reach_Flyer_column = f'Reach_Flyer_{segment}'
      media_executed = f'Executed_{path}'
      L1_reach_Flyer_column = f'Reach_Flyer_{segment}_L1'
      L2_reach_Flyer_column = f'Reach_Flyer_{segment}_L2'
      L3_reach_Flyer_column = f'Reach_Flyer_{segment}_L3'
      new_View_Flyer_column = f'View_Flyer_{segment}_via{path}'

      # Get mu and sd values
      mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_View_Flyer_column].iloc[0]
      sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_View_Flyer_column].iloc[0]

      # Calculate the new column and add it to the DataFrame
      df[new_View_Flyer_column] = (
          (df[base_reach_Flyer_column] + df[L1_reach_Flyer_column] + df[L2_reach_Flyer_column] + df[L3_reach_Flyer_column]) *
          df[media_executed] /100 *
          df[ViewRate_Flyer_column] *
            (norm.ppf(np.random.rand(len(df))) * sd + mu)
      )

      print(new_View_Flyer_column)

View_Flyer_Young_viaTV
View_Flyer_Middle_viaTV
View_Flyer_Elder_viaTV
View_Flyer_Young_viaDigital
View_Flyer_Middle_viaDigital
View_Flyer_Elder_viaDigital

In [ ]:
# Total View Flyer
# Define the lists of and segments to process
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each segments
for segment in segments:
    # Dynamically generate column names using f-strings from the media and segment names
    View_Flyer_Directly = f'View_Flyer_{segment}_Directly'
    View_Flyer_viaTV = f'View_Flyer_{segment}_viaTV'
    View_Flyer_viaDigital = f'View_Flyer_{segment}_viaDigital'
    total_View_Flyer_column = f'View_Flyer_{segment}'

    # Calculate the new column and add it to the DataFrame
    df[total_View_Flyer_column] = df[View_Flyer_Directly] + df[View_Flyer_viaTV] + df[View_Flyer_viaDigital]

##Sales Data

### Baseline by geo

In [ ]:
df = pd.merge(df, Share_by_geo_df, on=['Geo'], how='inner')

In [ ]:
# Baseline calculation directly from TotalGeoDemand
mu = 1.0
sd = 0.03  # Combined noise level

df['Baseline'] = (df['TotalGeoDemand'] * df['StoreCoverage_by_Geo'] * (1 + α8 * df['DemandShock']) * (norm.ppf(np.random.rand(len(df))) * sd + mu))

### Incremental Sales

In [ ]:
df = pd.merge(df, PurchaseRatio_df, on=['Week'], how='inner')

In [ ]:
#TV and Digital
# Define the lists of media types and segments to process
media_types = ['TV', 'Digital']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each media type
for media in media_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names using f-strings from the media and segment names
        Reach_column = f'Reach_{media}_{segment}'
        ConversionRate_column = f'ConversionRate_{media}_{segment}'
        UnitSales = eval(f'UnitSales_{media}_{segment}')
        new_sales_column = f'Sales_{media}_{segment}'

        # Get mu and sd values
        mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_sales_column].iloc[0]
        sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_sales_column].iloc[0]

        # Calculate the new column and add it to the DataFrame
        df[new_sales_column] = df[Reach_column] * df[ConversionRate_column] * df['TotalDemand'] * (1+ df['DemandShock']) *(norm.ppf(np.random.rand(len(df))) * sd + mu) * UnitSales

In [ ]:
#Flyer
# Define the lists of media types and segments to process
media_types = ['Flyer']
path_types = ['Directly', 'viaTV', 'viaDigital']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each media type
for media in media_types:
    # Inner loop to iterate through each segment
    for path in path_types:
      for segment in segments:
          # Dynamically generate column names using f-strings from the media and segment names
          View_column = f'View_{media}_{segment}_{path}'
          ConversionRate_column = f'ConversionRate_{media}_{segment}'
          UnitSales = eval(f'UnitSales_{media}_{segment}')
          new_sales_column = f'Sales_{media}_{path}_{segment}'

          # Get mu and sd values
          mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_sales_column].iloc[0]
          sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_sales_column].iloc[0]

          # Calculate the new column and add it to the DataFrame
          df[new_sales_column] = df[View_column] * df[ConversionRate_column] * df['TotalDemand'] * (1+ df['DemandShock']) *(norm.ppf(np.random.rand(len(df))) * sd + mu) * UnitSales
          print(new_sales_column)

Sales_Flyer_Directly_Young
Sales_Flyer_Directly_Middle
Sales_Flyer_Directly_Elder
Sales_Flyer_viaTV_Young
Sales_Flyer_viaTV_Middle
Sales_Flyer_viaTV_Elder
Sales_Flyer_viaDigital_Young
Sales_Flyer_viaDigital_Middle
Sales_Flyer_viaDigital_Elder

In [ ]:
#Need to have breakdown of flyer incremental sales

### Coupon Used, Sales and Discount

In [ ]:
df = pd.merge(df, CouponResponseRatio_df, on=['Week'], how='inner')

In [ ]:
#Coupon Used viaDigital
# Define the lists of media types and segments to process
segments = ['Young', 'Middle', 'Elder']

# Loop to iterate through each segment
for segment in segments:
    # Dynamically generate column names using f-strings from the media and segment names
    Reach_column = f'Reach_Digital_{segment}'
    CouponRedemptionRate_column = f'CouponRedemptionRate_Digital_{segment}'
    UnitSales = eval(f'UnitSales_Coupon_viaDigital_{segment}')
    CouponDiscountRate = eval(f'CouponDiscountRate_viaDigital_{segment}')

    new_CouponUsed_column = f'CouponUsed_viaDigital_{segment}'
    new_CouponSales_column =f'CouponSales_viaDigital_{segment}'
    new_CouponDiscount_column =f'CouponDiscount_viaDigital_{segment}'

    # Get mu and sd values
    mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_CouponUsed_column].iloc[0]
    sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_CouponUsed_column].iloc[0]

    # Calculate the new column and add it to the DataFrame
    df[new_CouponUsed_column] = df[Reach_column] * df[CouponRedemptionRate_column] * df['TotalDemand'] * (1+ df['DemandShock']) *(norm.ppf(np.random.rand(len(df))) * sd + mu)
    df[new_CouponSales_column] = df[new_CouponUsed_column] * UnitSales * (1- CouponDiscountRate)
    df[new_CouponDiscount_column] = df[new_CouponUsed_column] * UnitSales * CouponDiscountRate

In [ ]:
#Coupon Used viaFlyer
# Define the lists of media types and segments to process
path_types = ['Directly', 'viaTV', 'viaDigital']
segments = ['Young', 'Middle', 'Elder']

# Outer loop to iterate through each path type
for path in path_types:
    # Inner loop to iterate through each segment
    for segment in segments:
        # Dynamically generate column names using f-strings from the media and segment names
        View_column = f'View_Flyer_{segment}_{path}'
        CouponRedemptionRate_column = f'CouponRedemptionRate_Flyer_{segment}'
        UnitSales = eval(f'UnitSales_Coupon_viaFlyer_{segment}')
        CouponDiscountRate = eval(f'CouponDiscountRate_viaFlyer_{segment}')

        new_CouponUsed_column = f'CouponUsed_viaFlyer_{path}_{segment}'
        new_CouponSales_column =f'CouponSales_viaFlyer_{path}_{segment}'
        new_CouponDiscount_column =f'CouponDiscount_viaFlyer_{path}_{segment}'

        # Get mu and sd values
        mu = mu_sd_df[mu_sd_df['Metric'] == 'mu'][new_CouponUsed_column].iloc[0]
        sd = mu_sd_df[mu_sd_df['Metric'] == 'sd'][new_CouponUsed_column].iloc[0]

        # Calculate the new column and add it to the DataFrame
        df[new_CouponUsed_column] = df[View_column] * df[CouponRedemptionRate_column] * df['TotalDemand'] * (1+ df['DemandShock']) *(norm.ppf(np.random.rand(len(df))) * sd + mu)
        df[new_CouponSales_column] = df[new_CouponUsed_column] * UnitSales * (1- CouponDiscountRate)
        df[new_CouponDiscount_column] = df[new_CouponUsed_column] * UnitSales * CouponDiscountRate

In [ ]:
df['CouponDiscount_viaDigital'] = (
    df['CouponDiscount_viaDigital_Young'] + df['CouponDiscount_viaDigital_Middle'] + df['CouponDiscount_viaDigital_Elder'])

df['CouponDiscount_viaFlyer'] = (
    df['CouponDiscount_viaFlyer_Directly_Young'] + df['CouponDiscount_viaFlyer_Directly_Middle'] + df['CouponDiscount_viaFlyer_Directly_Elder'] +
    df['CouponDiscount_viaFlyer_viaTV_Young'] + df['CouponDiscount_viaFlyer_viaTV_Middle'] + df['CouponDiscount_viaFlyer_viaTV_Elder'] +
    df['CouponDiscount_viaFlyer_viaDigital_Young'] + df['CouponDiscount_viaFlyer_viaDigital_Middle'] + df['CouponDiscount_viaFlyer_viaDigital_Elder'])

df['CouponDiscount'] = (
    df['CouponDiscount_viaDigital'] + df['CouponDiscount_viaFlyer'])

### Incremental Sales Across Generations

In [ ]:
df['a_Sales_TV_direct'] = (
    df['Sales_TV_Young'] + df['Sales_TV_Middle'] + df['Sales_TV_Elder'])

df['b_Sales_TV_indirect_flyer_coupon'] = (
    df['CouponSales_viaFlyer_viaTV_Young'] + df['CouponSales_viaFlyer_viaTV_Middle'] + df['CouponSales_viaFlyer_viaTV_Elder'])

df['c_Sales_TV_indirect_flyer_no_coupon'] = (
    df['Sales_Flyer_viaTV_Young'] + df['Sales_Flyer_viaTV_Middle'] + df['Sales_Flyer_viaTV_Elder'])

df['d_Sales_Digital_direct'] = (
    df['Sales_Digital_Young'] + df['Sales_Digital_Middle'] + df['Sales_Digital_Elder'])

df['e_Sales_Digital_indirect_coupon'] = (
    df['CouponSales_viaDigital_Young'] + df['CouponSales_viaDigital_Middle'] + df['CouponSales_viaDigital_Elder'])

df['f_Sales_Digital_indirect_flyer_coupon'] = (
    df['CouponSales_viaFlyer_viaDigital_Young'] + df['CouponSales_viaFlyer_viaDigital_Middle'] + df['CouponSales_viaFlyer_viaDigital_Elder'])

df['g_Sales_Digital_indirect_flyer_no_coupon'] = (
    df['Sales_Flyer_viaDigital_Young'] + df['Sales_Flyer_viaDigital_Middle'] + df['Sales_Flyer_viaDigital_Elder'])

df['h_Sales_Flyer_direct'] = (
    df['Sales_Flyer_Directly_Young'] + df['Sales_Flyer_Directly_Middle'] + df['Sales_Flyer_Directly_Elder'])

df['i_Sales_Flyer_indirect_coupon'] = (
    df['CouponSales_viaFlyer_Directly_Young'] + df['CouponSales_viaFlyer_Directly_Middle'] + df['CouponSales_viaFlyer_Directly_Elder'])

### Baseline, Incremental Sales and Total Sales

In [ ]:
df['IncrementalSales'] = (
    df['a_Sales_TV_direct'] + df['b_Sales_TV_indirect_flyer_coupon'] + df['c_Sales_TV_indirect_flyer_no_coupon'] +
    df['d_Sales_Digital_direct'] + df['e_Sales_Digital_indirect_coupon'] + df['f_Sales_Digital_indirect_flyer_coupon'] + df['g_Sales_Digital_indirect_flyer_no_coupon'] +
    df['h_Sales_Flyer_direct'] + df['i_Sales_Flyer_indirect_coupon'])

df['Sales'] = df['Baseline'] + df['IncrementalSales']

In [ ]:
pd.set_option('display.max_columns', None)
display(df)
pd.reset_option('display.max_columns')

,Geo,Week,Holidays,DemandShock,TotalDemandSeasonality,TotalDemand,TotalGeoDemand,CostMultiplier_TV,Population,Pop_Young,Pop_Middle,Pop_Elder,ViewRate_Flyer_Young,ViewRate_Flyer_Middle,ViewRate_Flyer_Elder,TotalDemandSeasonality(intentionaly),Type_of_Plan_TV,Type_of_Plan_Digital,Type_of_Plan_Flyer,Plan_TV,Plan_Digital,Plan_Flyer,Executed_TV,Executed_Digital,Executed_Flyer,UnitCost_TV,UnitCost_Flyer,Impression_TV,Impression_Digital,Impression_Flyer,National_Population,Spend_TV,Spend_Digital,Spend_Flyer,Impression_TV_Young,Impression_TV_Middle,Impression_TV_Elder,Impression_Digital_Young,Impression_Digital_Middle,Impression_Digital_Elder,Impression_Flyer_Young,Impression_Flyer_Middle,Impression_Flyer_Elder,Frequency_TV,Frequency_Digital,Frequency_Flyer,Reach_TV_Young,Reach_TV_Middle,Reach_TV_Elder,Reach_Digital_Young,Reach_Digital_Middle,Reach_Digital_Elder,Reach_Flyer_Young,Reach_Flyer_Middle,Reach_Flyer_Elder,Reach_Flyer_Young_L1,Reach_Flyer_Middle_L1,Reach_Flyer_Elder_L1,Reach_Flyer_Young_L2,Reach_Flyer_Middle_L2,Reach_Flyer_Elder_L2,Reach_Flyer_Young_L3,Reach_Flyer_Middle_L3,Reach_Flyer_Elder_L3,View_Flyer_Young_Directly,View_Flyer_Middle_Directly,View_Flyer_Elder_Directly,View_Flyer_Young_viaTV,View_Flyer_Middle_viaTV,View_Flyer_Elder_viaTV,View_Flyer_Young_viaDigital,View_Flyer_Middle_viaDigital,View_Flyer_Elder_viaDigital,View_Flyer_Young,View_Flyer_Middle,View_Flyer_Elder,StoreCoverage_by_Geo,Baseline,ConversionRate_TV_Young,ConversionRate_TV_Middle,ConversionRate_TV_Elder,ConversionRate_Flyer_Young,ConversionRate_Flyer_Middle,ConversionRate_Flyer_Elder,ConversionRate_Digital_Young,ConversionRate_Digital_Middle,ConversionRate_Digital_Elder,Sales_TV_Young,Sales_TV_Middle,Sales_TV_Elder,Sales_Digital_Young,Sales_Digital_Middle,Sales_Digital_Elder,Sales_Flyer_Directly_Young,Sales_Flyer_Directly_Middle,Sales_Flyer_Directly_Elder,Sales_Flyer_viaTV_Young,Sales_Flyer_viaTV_Middle,Sales_Flyer_viaTV_Elder,Sales_Flyer_viaDigital_Young,Sales_Flyer_viaDigital_Middle,Sales_Flyer_viaDigital_Elder,CouponRedemptionRate_TV_Young,CouponRedemptionRate_TV_Middle,CouponRedemptionRate_TV_Elder,CouponRedemptionRate_Flyer_Young,CouponRedemptionRate_Flyer_Middle,CouponRedemptionRate_Flyer_Elder,CouponRedemptionRate_Digital_Young,CouponRedemptionRate_Digital_Middle,CouponRedemptionRate_Digital_Elder,CouponUsed_viaDigital_Young,CouponSales_viaDigital_Young,CouponDiscount_viaDigital_Young,CouponUsed_viaDigital_Middle,CouponSales_viaDigital_Middle,CouponDiscount_viaDigital_Middle,CouponUsed_viaDigital_Elder,CouponSales_viaDigital_Elder,CouponDiscount_viaDigital_Elder,CouponUsed_viaFlyer_Directly_Young,CouponSales_viaFlyer_Directly_Young,CouponDiscount_viaFlyer_Directly_Young,CouponUsed_viaFlyer_Directly_Middle,CouponSales_viaFlyer_Directly_Middle,CouponDiscount_viaFlyer_Directly_Middle,CouponUsed_viaFlyer_Directly_Elder,CouponSales_viaFlyer_Directly_Elder,CouponDiscount_viaFlyer_Directly_Elder,CouponUsed_viaFlyer_viaTV_Young,CouponSales_viaFlyer_viaTV_Young,CouponDiscount_viaFlyer_viaTV_Young,CouponUsed_viaFlyer_viaTV_Middle,CouponSales_viaFlyer_viaTV_Middle,CouponDiscount_viaFlyer_viaTV_Middle,CouponUsed_viaFlyer_viaTV_Elder,CouponSales_viaFlyer_viaTV_Elder,CouponDiscount_viaFlyer_viaTV_Elder,CouponUsed_viaFlyer_viaDigital_Young,CouponSales_viaFlyer_viaDigital_Young,CouponDiscount_viaFlyer_viaDigital_Young,CouponUsed_viaFlyer_viaDigital_Middle,CouponSales_viaFlyer_viaDigital_Middle,CouponDiscount_viaFlyer_viaDigital_Middle,CouponUsed_viaFlyer_viaDigital_Elder,CouponSales_viaFlyer_viaDigital_Elder,CouponDiscount_viaFlyer_viaDigital_Elder,CouponDiscount_viaDigital,CouponDiscount_viaFlyer,CouponDiscount,a_Sales_TV_direct,b_Sales_TV_indirect_flyer_coupon,c_Sales_TV_indirect_flyer_no_coupon,d_Sales_Digital_direct,e_Sales_Digital_indirect_coupon,f_Sales_Digital_indirect_flyer_coupon,g_Sales_Digital_indirect_flyer_no_coupon,h_Sales_Flyer_direct,i_Sales_Flyer_indirect_coupon,IncrementalSales,Sales
0,1,3/1/2021,0,0,0.966291,0.964059,4.661643e+07,1.0,36227.421289,9404.743939,14895.100585,11927.576771,0.347367,0.561553,0.765927,0.963201,NoSpend_Period,NoSpend_Period,NoSpend_Period,0,0,0,0.000000,0.000000,0.000000,155000.0,10.75,0.000000,0.000000,0.000000,102478.054640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010,486648.619613,0.234332,0.231320,0.194168,0.125015,0.234857,0.229182,0.154407,0.140798,0.158444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018941,0.030812,0.038299,0.051304,0.057110,0.050098,0.050647,0.061119,0.058551,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,486648.619613
1,1,3/8/2021,0,0,0.979547,0.977021,4.724316e+07,1.0,36222.977347,9403.584953,14891.261735,11928.130664,0.345555,0.558768,0.763744,0.995727,Normal Period,Normal Period,Normal Period,0,0,0,0.000000,0.000000,0.000000,155000.0,10.75,0.000000,0.000000,0.000000,102465.483870,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010,470940.666114,0.234875,0.231578,0.195021,0.126146,0.235372,0.229847,0.154884,0.140899,0.160088,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019052,0.030801,0.038579,0.051463,0.057577,0.051123,0.052041,0.062449,0.058883,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,470940.666114
2,1,3/15/2021,0,0,1.011943,1.009201,4.879920e+07,1.0,36215.793032,9398.795409,14888.068705,11928.928921,0.343767,0.556030,0.761597,1.018205,Low Intensity,Low Intensity,Low Intensity,0,80,20,0.000000,83.177129,17.726351,155000.0,10.75,0.000000,30123.256727,6419.738636,102445.161290,0.000000,8951.665927,27604.876135,0.000000,0.000000,0.000000,7821.669452,12736.105495,9565.481779,1749.734211,2556.810307,2113.194118,0.000000,1.950941,1.002991,0.000000,0.000000,0.000000,4009.177069,6528.184605,4903.008295,1744.516039,2549.185220,2106.892012,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,584.480155,1507.100438,1594.378703,0.000000,0.000000,0.000000,487.403114,1172.247473,1329.550771,1071.883268,2679.347911,2923.929473,0.010,524880.504626,0.235393,0.231830,0.195868,0.127230,0.235841,0.230492,0.155347,0.141002,0.161705,0.000000,0.000000,0.000000,3714.626703,6428.934141,4611.114301,423.115943,1555.854677,1349.566412,0.000000,0.000000,0.000000,259.525323,1262.965874,1502.716814,0.019163,0.030794,0.038857,0.051621,0.058037,0.052127,0.053400,0.063745,0.059219,206.940440,982.967092,51.735110,367.724828,1746.692933,91.931207,267.305915,1269.703094,66.826479,23.961943,113.819228,5.990486,70.439396,334.587132,17.609849,88.898585,422.268278,22.224646,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,32.582205,154.765474,8.145551,57.769774,274.406428,14.442444,56.624986,268.968685,14.156247,210.492796,82.569222,293.062018,0.000000,0.00000,0.000000,14754.675145,3999.363119,698.140586,3025.208010,3328.537032,870.674638,26676.598531,551557.103157
3,1,3/22/2021,0,0,1.018055,1.036003,5.009520e+07,1.0,36208.608718,9394.005866,14884.875675,11929.727179,0.342002,0.553340,0.759484,1.020599,Low Intensity,Low Intensity,Low Intensity,0,80,20,0.000000,86.027370,19.244488,155000.0,10.75,0.000000,31149.313690,6968.161511,102424.838709,0.000000,9398.384489,29963.094499,0.000000,0.000000,0.000000,8099.785031,12875.026395,10174.502264,1794.399041,2873.998444,2299.764027,0.000000,2.171106,0.998381,0.000000,0.000000,0.000000,3730.717804,5930.168519,4686.321502,1797.309424,2878.659857,2303.494075,872.258019,1274.592610,1053.446006,0.00000,0.000000,0.000000,0.0,0.0,0.0,916.756467,2272.108203,2548.139061,0.000000,0.000000,0.000000,762.828689,2146.783412,2214.976094,1679.585157,4418.891616,4763.115154,0.010,501061.013615,0.235886,0.232075,0.196709,0.128264,0.236265,0.231116,0.155795,0.141105,0.163292,0.000000,0.000000,0.000000,2993.121065,3749.049628,3869.712684,579.630787,3015.412292,3071.056867,0.000000,0.000000,0.000000,552.284122,3506.034292,2424.815672,0.019272,0.030789,0.039136,0.051779,0.058488,0.053111,0.054725,0.065007,0.059559,198.537559,943.053405,49.634390,454.201501,2157.457130,113.550375,301.296184,1431.156874,75.324046,65.755305,312.337698,16.438826,134.173172,637.322565,33.543293,119.161573,566.017471,29.790393,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,31.497678,149.613970,7.874419,158.485647,752.806822,39.621412,129.859991,616.834955,32.464998,238.508811,159.733341,398.242152,0.000000,0.00000,0.000000,10611.883377,4531.667409,1519.255747,6483.134086,6666.099947,1515.677733,31327.718299,532388.731914
4,1,3/29/2021,0,0,0.941146,0.950452,4.595847e+07,1.0,36201.424403,9389.216322,14881.682645,11930.525436,0.340261,0.550698,0.757407,0.931632,NoSpend_Period,NoSpend_Period,NoSpend_Period,0,0,0,0.000000,0.000000,0.000000,155000.0,10.75,0.000000,0.000000,0.000000,102404.516129,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,898.654712,1439.329928,1151.747037,436.12901,637.296305,526.723003,0.0,0.0,0.0,440.738476,1180.699110,1297.688986,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,440.738476,1180.699110,1297.688986,0.010,456766.958060,0.236356,0.232315,0.197544,0.129251,0.236645,0.231720,0.156229,0.141209,0.164852,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,216.192792,2026.797698,1471.208482,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019381,0.030787,0.039413,0.051937,0.058931,0.054075,0.056014,0.066234,0.059903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.363260,110.975485,5.840815,32.522763,154.483126,8.130691,81.158198,385.501441,20.289550,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,34.261055,34.261055,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3714.198971,650.960052,4365.159023,461132.117083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6025,30,12/2/2024,0,0,1.028000,1.047716,1.696974e+06,1.1,1204.029585,308.229827,500.058032,395.741725,0.240295,0.406597,0.586035,1.021472,Low Intensity,Low Intensity,Low Intensity,0,100,0,0.000000,97.516943,0.000000,5115.0,13.23,0.000000,1174.132845,0.000000,101679.723505,0.000000,375.464759,0.000000,0.000000,0.000000,0.000000,300.887887,519.483983,353.760976,0.000000,0.000000,0.000000,0.000000,1.891754,0.000000,0.000000,0.000000,0.000000,159.052310,274.604367,187.001547,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004,6681.948247,0.211323,0.209228,0.205907,0.089565,0.187450,0.277124,0.130876,0.141073,0.164654,0.000000,0.000000,0.000000,87.766680,274.769074,169.322226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.021162,0.042347,0.063435,0.058176,0.076711,0.075766,0.070310,0.102615,0.135372,9.124333,43.340583,2.281083,34.687360,164.764960,8.671840,32.913136,156.337398,8.228284,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.181207,0.000000,19.181207,0.000000,0.00000,0.000000,531.857979,364.442940,0.000000,0.000000,0.000000,0.000000,896.300919,7578.249167
6026,30,12/9/2024,0,0,1.048000,1.082211,1.752844e+06,1.1,1203.987021,308.208546,500.084953,395.693522,0.240010,0.406228,0.585352,1.060044,Medium Intensity,Medium Intensity,Medium Intensity,150,140,0,176.427722,132.017156,0.000000,5115.0,13.23,2124.166872,1589.469419,0.000000,101676.129035,902.427797,592.639480,0.000000,525.139999,901.451449,697.575425,406.918726,645.067956,537.482737,0.000000,0.000000,0.000000,1.689079,2.205998,0.000000,310.903101,533.693970,412.991513,184.460133,292.415447,243.646043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004,7168.915158,0.211898,0.209383,0.204645,0.088414,0.186335,0.277756,0.131320,0.141475,0.164505,348.335453,635.218748,363.754385,115.083817,222.939204,127.067733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020915,0.042485,0.062922,0.058347,0.076776,0.075399,0.069835,0.102085,0.136569,13.269935,63.032190,3.317484,29.967061,142.343539,7.491765,38.854410,184.558448,9.713603,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.522851,0.000000,20.522851,1347.308587,0.00000,0.000000,465.090754,389.934178,0.000000,0.000000,0.000000,0.000000,2202.333518,9371.248676
6027,30,12/16/2024,0,1,1.097000,1.128459,1.827751e+06,1.1,1203.933544,308.181807,500.111691,395.640045,0.239726,0.405870,0.584680,1.084586,Medium Intensity,Medium Intensity,Medium Intensity,150,140,0,145.248554,120.203685,0.000000,5115.0,13.23,1748.696064,1447.172480,0.000000,101671.612905,742.946354,505.552193,0.000000,453.930436,720.031047,574.734581,370.169999,596.803069,480.199412,0.000000,0.000000,0.000000,1.490146,2.353642,0.000000,304.621526,483.195086,385.690210,157.275420,253.565805,204.024002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004,8300.981175,0.212479,0.209546,0.203367,0.087226,0.185177,0.278387,0.131776,0.141887,0.164359,761.766272,1129.144335,894.642280,204.979798,303.929852,323.028709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020664,0.042625,0.062398,0.058524,0.076839,0.075021,0.069343,0.101532,0.137785,25.478561,121.023165,6.369640,55.428809,263.286845,13.857202,68.438834,325.084463,17.109709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,37.336551,0.000000,37.336551,2785.552888,0.00000,0.000000,831.938359,709.394473,0.000000,0.000000,0.000000,0.000000,4326.885720,12627.866895
6028,30,12/23/2024,0,0,1.099000,1.090485,1.766245e+06,1.1,1203.880067,308.155068,500.138430,395.586568,0.239443,0.405523,0.584019,1.105405,High Intensity,High Intensity,High Intensity,350,280,40,269.093685,261.775761,46.571171,5115.0,13.23,3239.565232,3151.466204,560.661050,101667.096776,1376.414198,1607.618857,2967.018276,881.467371,1293.090349,1065.007512,805.977231,1304.414865,1041.074109,154.037600,222.242732,184.380718,1.865214,3.387435,1.010702,472.582456,693.266516,570.984114,237.931432,385.074521,307.334058,152.406493,219.889398,182.428306,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,36.973579,86.269352,107.172370,101.045719,243.929768,286.256574,90.575371,210.870065,278.907613,228.594668,541.069185,672.336557,0.004,7016.722246,0.213065,0.209716,0.202071,0.086000,0.183975,0.279015,0.132243,0.142311,0.164216,567.088993,739.860014,591.457267,138.324589,289.164494,260.568623,18.757260,46.186706,204.292165,43.516524,250.762176,452.233703,41.235387,251.501884,350.470987,0.020409,0.042769,0.061863,0.058705,0.076902,0.074632,0.068834,0.100955,0.139020,17.129853,81.366802,4.282463,44.876224,213.162063,11.219056,47.074090,223.601930,11.768523,2.292805,10.890822,0.573201,6.054578,28.759244,1.513644,7.293535,34.644291,1.823384,4.376748,20.789554,1.094187,18.746354,89.04518,4.686588,22.805927,108.328155,5.701482,3.855520,18.313721,0.963880,16.833273,79.958047,4.208318,21.077778,100.119445,5.269444,27.270042,25.834129,53.104171,1898.406274,218.16289,746.512403,688.057706,518.130795,198.391214,643.208258,269.236131,74.294357,5254.400026,12271.122272
6029,30,12/30/2024,1,0,0.828000,0.872891,1.413811e+06,1.1,1203.826589,308.128330,500.165169,395.533091,0.239161,0.405187,0.583368,0.817444,NoSpend_Period,NoSpend_Period,NoSpend_Period,0,120,40,0.000000,90.696428,41.103627,5115.0,13.23,0.000000,1091.827718,494.816388,101662.580646,0.000000,335.407625,2618.568324,0.000000,0.000000,0.000000,279.603904,448.990257,363.233557,130.934045,201.177707,162.704636,0.000000,2.143106,1.010131,0.000000,0.000000,0.000000,130.466661,209.504442,169.489298,129.620893,199.160075,161.072854,76.203246,109.944699,91.214153,0.00000,0.000000,0.000000,0.0,0.0,0.0,46.726696,127.362045,145.176162,0.000000,0.000000,0.000000,45.223887,112.477139,131.492351,91.950582,239.839185,276.668513,0.004,5458.687237,0.213659,0.209895,0.200757,0.084737,0.182729,0.279642,0.132722,0.142747,0.164078,0.000000,0.000000,0.000000,65.789843,101.285096,121.409996,17.805886,70.840383,197.557401,0.000000,0.000000,0.000000,16.293181,72.355450,202.704918,0.020150,0.042915,0.061317,0.058891,0.076965,0.074233,0.068308,0.100353,0.140275,8.001154,38.005483,2.000289,20.455547,97.163848,5.113887,27.113696,128.790055,6.778424,2.847648,13.526330,0.711912,10.583926,50.273649,2.645982,10.027053,47.628500,2.506763,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.743866,8.283365,0.435967,5.678757,26.974097,1.419689,9.476047,45.011224,2.369012,13.892599,10.089324,23.981924,0.000000,0.00000,0.000000,288.484935,263.959385,80.268686,291.353549,286.203669,111.428479,1321.698704,6780.385941

In [ ]:
# 1) Calculate TV_ROI
tv_sales_cols = ['a_Sales_TV_direct', 'b_Sales_TV_indirect_flyer_coupon', 'c_Sales_TV_indirect_flyer_no_coupon']
tv_spend_col = 'Spend_TV'
TV_ROI = df[tv_sales_cols].sum().sum() / df[tv_spend_col].sum()
print(f"TV ROI: {TV_ROI}")

# 2) Calculate Digital_ROI
digital_sales_cols = ['d_Sales_Digital_direct', 'e_Sales_Digital_indirect_coupon', 'f_Sales_Digital_indirect_flyer_coupon', 'g_Sales_Digital_indirect_flyer_no_coupon']
digital_spend_col = 'Spend_Digital'
Digital_ROI = df[digital_sales_cols].sum().sum() / df[digital_spend_col].sum()
print(f"Digital ROI: {Digital_ROI}")

# 3) Calculate Flyer_ROI
flyer_sales_cols = ['h_Sales_Flyer_direct', 'i_Sales_Flyer_indirect_coupon', 'b_Sales_TV_indirect_flyer_coupon', 'c_Sales_TV_indirect_flyer_no_coupon',
                    'f_Sales_Digital_indirect_flyer_coupon', 'g_Sales_Digital_indirect_flyer_no_coupon']
flyer_spend_col = 'Spend_Flyer'
Flyer_ROI = df[flyer_sales_cols].sum().sum() / df[flyer_spend_col].sum()
print(f"Flyer ROI: {Flyer_ROI}")

TV ROI: 2.5117732574564053
Digital ROI: 2.280533467879035
Flyer ROI: 0.8249506694848818


##(Skippable)Export dataframe

In [ ]:
# # Define the export path
# export_path = 'df_exported.csv'

# # Export the dataframe to CSV
# df.to_csv(export_path, index=False)

# print(f"DataFrame successfully exported to: {export_path}")